# Generated by Django 4.2.1 on 2023-06-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.area'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.autor'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='areas',
            field=models.ManyToManyField(to='portfolio.area'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artigo'),
        ),
    ]
