# Generated by Django 4.2.2 on 2023-06-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cadeira_pessoa_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoMetereologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
