# Generated by Django 4.2.2 on 2023-06-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_previsaometereologica'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsaometereologica',
            name='temp_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previsaometereologica',
            name='temp_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
