# Generated by Django 4.2.2 on 2023-06-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_previsaometereologica_temp_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
