# Generated by Django 4.2.2 on 2023-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_artigo_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descricao', models.TextField(max_length=500)),
                ('ano', models.IntegerField()),
                ('link', models.TextField()),
                ('github', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('autor', models.ManyToManyField(related_name='autor', to='portfolio.pessoa')),
                ('orientador', models.ManyToManyField(related_name='orientador', to='portfolio.pessoa')),
            ],
        ),
    ]
